import type { I18nMap } from "./types";

/**
 * EnumOption 表的种子数据（仅 `prisma/seed.ts` 使用）。
 * 标签内容即原先硬编码在 `meta.ts` 里的 TYPE_META / CATEGORY_META / PRICING_META，
 * 以及 messages 里 dashboard.status 的多语言文案。
 */

export type SeedOption = {
  value: string;
  labelI18n: I18nMap;
  sortOrder: number;
};

export const TYPE_SEED: SeedOption[] = [
  {
    value: "tool",
    sortOrder: 1,
    labelI18n: {
      zh: "工具",
      "zh-TW": "工具",
      en: "Tools",
      ja: "ツール",
      ru: "Инструменты",
      ko: "도구",
      es: "Herramientas",
      fr: "Outils",
      de: "Tools",
    },
  },
  {
    value: "model",
    sortOrder: 2,
    labelI18n: {
      zh: "模型",
      "zh-TW": "模型",
      en: "Models",
      ja: "モデル",
      ru: "Модели",
      ko: "모델",
      es: "Modelos",
      fr: "Modèles",
      de: "Modelle",
    },
  },
  {
    value: "agent",
    sortOrder: 3,
    labelI18n: {
      zh: "Agent",
      "zh-TW": "Agent",
      en: "Agents",
      ja: "エージェント",
      ru: "Агенты",
      ko: "에이전트",
      es: "Agentes",
      fr: "Agents",
      de: "Agenten",
    },
  },
  {
    value: "learning",
    sortOrder: 4,
    labelI18n: {
      zh: "学习",
      "zh-TW": "學習",
      en: "Learning",
      ja: "学習",
      ru: "Обучение",
      ko: "학습",
      es: "Aprendizaje",
      fr: "Apprentissage",
      de: "Lernen",
    },
  },
  {
    value: "skill",
    sortOrder: 5,
    labelI18n: {
      zh: "SKILLs",
      "zh-TW": "SKILLs",
      en: "SKILLs",
      ja: "SKILLs",
      ru: "SKILLs",
      ko: "SKILLs",
      es: "SKILLs",
      fr: "SKILLs",
      de: "SKILLs",
    },
  },
  {
    value: "prompt",
    sortOrder: 6,
    labelI18n: {
      zh: "提示词",
      "zh-TW": "提示詞",
      en: "Prompts",
      ja: "プロンプト",
      ru: "Промпты",
      ko: "프롬프트",
      es: "Prompts",
      fr: "Prompts",
      de: "Prompts",
    },
  },
  {
    value: "dataset",
    sortOrder: 7,
    labelI18n: {
      zh: "数据集",
      "zh-TW": "資料集",
      en: "DataSets",
      ja: "データセット",
      ru: "Датасеты",
      ko: "데이터셋",
      es: "Conjuntos de datos",
      fr: "Jeux de données",
      de: "Datensätze",
    },
  },
];

export const CATEGORY_SEED: SeedOption[] = [
  {
    value: "chat",
    sortOrder: 1,
    labelI18n: {
      zh: "对话助手",
      "zh-TW": "對話助手",
      en: "Chatbots",
      ja: "チャットボット",
      ru: "Чат-боты",
      ko: "챗봇",
      es: "Chatbots",
      fr: "Chatbots",
      de: "Chatbots",
    },
  },
  {
    value: "image",
    sortOrder: 2,
    labelI18n: {
      zh: "图像生成",
      "zh-TW": "圖像生成",
      en: "Image",
      ja: "画像",
      ru: "Изображения",
      ko: "이미지",
      es: "Imagen",
      fr: "Image",
      de: "Bild",
    },
  },
  {
    value: "video",
    sortOrder: 3,
    labelI18n: {
      zh: "视频生成",
      "zh-TW": "影片生成",
      en: "Video",
      ja: "動画",
      ru: "Видео",
      ko: "비디오",
      es: "Vídeo",
      fr: "Vidéo",
      de: "Video",
    },
  },
  {
    value: "audio",
    sortOrder: 4,
    labelI18n: {
      zh: "音频语音",
      "zh-TW": "音訊語音",
      en: "Audio",
      ja: "音声",
      ru: "Аудио",
      ko: "오디오",
      es: "Audio",
      fr: "Audio",
      de: "Audio",
    },
  },
  {
    value: "code",
    sortOrder: 5,
    labelI18n: {
      zh: "编程开发",
      "zh-TW": "程式開發",
      en: "Coding",
      ja: "コーディング",
      ru: "Программирование",
      ko: "코딩",
      es: "Programación",
      fr: "Code",
      de: "Programmierung",
    },
  },
  {
    value: "writing",
    sortOrder: 6,
    labelI18n: {
      zh: "写作文案",
      "zh-TW": "寫作文案",
      en: "Writing",
      ja: "ライティング",
      ru: "Письмо",
      ko: "글쓰기",
      es: "Escritura",
      fr: "Rédaction",
      de: "Schreiben",
    },
  },
  {
    value: "productivity",
    sortOrder: 7,
    labelI18n: {
      zh: "效率办公",
      "zh-TW": "效率辦公",
      en: "Productivity",
      ja: "生産性",
      ru: "Продуктивность",
      ko: "생산성",
      es: "Productividad",
      fr: "Productivité",
      de: "Produktivität",
    },
  },
  {
    value: "search",
    sortOrder: 8,
    labelI18n: {
      zh: "搜索问答",
      "zh-TW": "搜尋問答",
      en: "Search",
      ja: "検索",
      ru: "Поиск",
      ko: "검색",
      es: "Búsqueda",
      fr: "Recherche",
      de: "Suche",
    },
  },
  {
    value: "research",
    sortOrder: 9,
    labelI18n: {
      zh: "学术研究",
      "zh-TW": "學術研究",
      en: "Research",
      ja: "研究",
      ru: "Исследования",
      ko: "연구",
      es: "Investigación",
      fr: "Recherche",
      de: "Forschung",
    },
  },
  {
    value: "data",
    sortOrder: 10,
    labelI18n: {
      zh: "数据分析",
      "zh-TW": "資料分析",
      en: "Data",
      ja: "データ",
      ru: "Данные",
      ko: "데이터",
      es: "Datos",
      fr: "Données",
      de: "Daten",
    },
  },
  {
    value: "multimodal",
    sortOrder: 11,
    labelI18n: {
      zh: "多模态",
      "zh-TW": "多模態",
      en: "Multimodal",
      ja: "マルチモーダル",
      ru: "Мультимодальный",
      ko: "멀티모달",
      es: "Multimodal",
      fr: "Multimodal",
      de: "Multimodal",
    },
  },
  {
    value: "framework",
    sortOrder: 12,
    labelI18n: {
      zh: "开发框架",
      "zh-TW": "開發框架",
      en: "Framework",
      ja: "フレームワーク",
      ru: "Фреймворк",
      ko: "프레임워크",
      es: "Framework",
      fr: "Framework",
      de: "Framework",
    },
  },
];

export const PRICING_SEED: SeedOption[] = [
  {
    value: "free",
    sortOrder: 1,
    labelI18n: {
      zh: "免费",
      "zh-TW": "免費",
      en: "Free",
      ja: "無料",
      ru: "Бесплатно",
      ko: "무료",
      es: "Gratis",
      fr: "Gratuit",
      de: "Kostenlos",
    },
  },
  {
    value: "freemium",
    sortOrder: 2,
    labelI18n: {
      zh: "部分免费",
      "zh-TW": "部分免費",
      en: "Freemium",
      ja: "一部無料",
      ru: "Freemium",
      ko: "부분 유료",
      es: "Freemium",
      fr: "Freemium",
      de: "Freemium",
    },
  },
  {
    value: "paid",
    sortOrder: 3,
    labelI18n: {
      zh: "付费",
      "zh-TW": "付費",
      en: "Paid",
      ja: "有料",
      ru: "Платно",
      ko: "유료",
      es: "De pago",
      fr: "Payant",
      de: "Kostenpflichtig",
    },
  },
];

export const STATUS_SEED: SeedOption[] = [
  {
    value: "PENDING",
    sortOrder: 1,
    labelI18n: {
      zh: "待审核",
      "zh-TW": "待審核",
      en: "Pending",
      ja: "審査待ち",
      ru: "На проверке",
      ko: "검토 대기",
      es: "Pendiente",
      fr: "En attente",
      de: "Ausstehend",
    },
  },
  {
    value: "PUBLISHED",
    sortOrder: 2,
    labelI18n: {
      zh: "已上架",
      "zh-TW": "已上架",
      en: "Published",
      ja: "公開済み",
      ru: "Опубликовано",
      ko: "게시됨",
      es: "Publicado",
      fr: "Publié",
      de: "Veröffentlicht",
    },
  },
  {
    value: "REJECTED",
    sortOrder: 3,
    labelI18n: {
      zh: "已驳回",
      "zh-TW": "已駁回",
      en: "Rejected",
      ja: "却下",
      ru: "Отклонено",
      ko: "거부됨",
      es: "Rechazado",
      fr: "Rejeté",
      de: "Abgelehnt",
    },
  },
];
